author:
  host: "localhost"
  port: 9090
  tls: false
  caFile: ""
  masterKey: "masterKey"

executor:
  host: "localhost"
  port: 9094
  tls: false
  caFile: ""

server:
  host: "0.0.0.0"
  port: "8080"
  exceptServiceKey: true